language: node_js  # this specifies the programming langiage used for the integration
node_js:  #this specifies the version of node_js used for this project
  - "8"
dist: trusty  #this is the type of server this ci is running on
services:  #..this se=pecifies the array of services that travis ci will install to run the application in the VM
  -mongodb
  -redis-server
env:  #this is the environmental variables used for the ci
  - NODE_ENV=ci # ...it routes us to the directory of the ci keys
  - PORT=3000
cache: #this is to confusing, but it installs the other set pf directories that where ommitted during push of codebase to github
  directories:
    - node_modules
    - client/node_modules
    yarn: true
install: #..package manger used, to install the node_modules
  - yarn install
  - yarn run build
scripts: #..this consist of the sets of commands that will run our travis ci configuration
  - nohup yarn start &
  - sleep 3
  - yarn run test